# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-31 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mitglied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=50, verbose_name='Vorname')),
                ('nachname', models.CharField(max_length=50, verbose_name='Nachname')),
                ('anschrift', models.CharField(max_length=50, verbose_name='Anschrift')),
                ('plz', models.CharField(max_length=50, verbose_name='PLZ/Ort')),
                ('geburtsdatum', models.DateField(verbose_name='Geburtsdatum')),
                ('telefon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon')),
                ('mobil', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mobil')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='Email')),
                ('iban', models.CharField(max_length=50, verbose_name='IBAN')),
                ('bic', models.CharField(max_length=50, verbose_name='Bic')),
                ('bank', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bank')),
                ('kontoinhaber', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kontoinhaber')),
                ('lastschrift', models.BooleanField(default=False, verbose_name='Lastschrift aktiv')),
                ('barzahler', models.BooleanField(default=False, verbose_name='Barzahler')),
                ('betrag', models.FloatField(verbose_name='Betrag')),
            ],
        ),
    ]
