# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitglied',
            name='mandatsreferenz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Mandatsreferenz'),
        ),
    ]
