# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0002_mitglied_mandatsreferenz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mitglied',
            name='betrag',
            field=models.CharField(choices=[('20', '20'), ('100', '100')], default='20', max_length=5, verbose_name='Betrag'),
        ),
    ]
