# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0003_auto_20160604_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitglied',
            name='mailverteiler',
            field=models.BooleanField(default=True, verbose_name='Mailverteiler'),
        ),
    ]
