# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-31 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='is_Active',
            field=models.BooleanField(default=True),
        ),
    ]
